### Step 0
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

In [39]:
import pandas as pd
energy = pd.read_excel('data/Energy Indicators.xls',skiprows = range(1,18),skipfooter = 38,header = 0,usecols=range(2,6),names=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable'],na_values=['...'])                            
energy['Energy Supply']=energy['Energy Supply']*1000000

#begining of function
def delete_nums(text):
    
    clean_list = [item for item in text if (not item.isdigit() and item != "(" and item != ")" ) ]
    clean_text="".join(clean_list)
    
    return clean_text
#end of function
energy['Country'] = energy['Country'].apply(delete_nums)


# replaccing values
energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States",
                           "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
                           "China, Hong Kong Special Administrative Region": "Hong Kong",
                           "Bolivia Plurinational State of": "Bolivia","Iran Islamic Republic of":"Iran"}, inplace=True)

#deleting numbers and parnthes 



energy.head(20)

                Country  Energy Supply  Energy Supply per Capita  % Renewable
0           Afghanistan   3.210000e+08                      10.0    78.669280
1               Albania   1.020000e+08                      35.0   100.000000
2               Algeria   1.959000e+09                      51.0     0.551010
3        American Samoa            NaN                       NaN     0.641026
4               Andorra   9.000000e+06                     121.0    88.695650
5                Angola   6.420000e+08                      27.0    70.909090
6              Anguilla   2.000000e+06                     136.0     0.000000
7   Antigua and Barbuda   8.000000e+06                      84.0     0.000000
8             Argentina   3.378000e+09                      79.0    24.064520
9               Armenia   1.430000e+08                      48.0    28.236060
10                Aruba   1.200000e+07                     120.0    14.870690
11            Australia   5.386000e+09                     231.0    11.810810
12              Austria   1.391000e+09                     164.0    72.452820
13           Azerbaijan   5.670000e+08                      60.0     6.384345
14              Bahamas   4.500000e+07                     118.0     0.000000
15              Bahrain   5.740000e+08                     425.0     0.000000
16           Bangladesh   1.625000e+09                      10.0     1.966329
17             Barbados   1.900000e+07                      69.0     0.000000
18              Belarus   1.142000e+09                     120.0     0.463389
19              Belgium   2.338000e+09                     210.0     9.959739

In [5]:
energy[energy['Country'] == 'Iran']

   Country  Energy Supply  Energy Supply per Capita  % Renewable
98    Iran   9.172000e+09                     119.0     5.707721

In [6]:
#for c in string:
#        if( not c.isdigit() and c != "(" and c != ")"):
#            new_string.append(c)
#    return "".join(new_string)

In [7]:
#begining of function
#def delete_nums(text):
    
#    clean_list = [item for item in text if (not item.isdigit() and item != "(" and item != ")" ) ]
#    clean_text="".join(clean_list)
    
#    return clean_text
#end of function

In [8]:
#energy['Country'] = energy['Country'].apply(delete_nums)

#energy.head(50)

In [9]:
#another solution
#energy.replace(to_replace =["(", ")"],  value ="")

In [10]:
#energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States",
#                           "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
#                           "China, Hong Kong Special Administrative Region": "Hong Kong",
#                           "Bolivia (Plurinational State of)": "Bolivia", "Switzerland17": "Switzerland"}, inplace=True)
#energy.head(50)

In [11]:
#for c in string:
#        if( not c.isdigit() and c != "(" and c != ")"):
#            new_string.append(c)
#    return "".join(new_string)

In [12]:
#energy['Country'] = energy['Country'].apply(delete_nums)
#energy.head(50)

In [13]:
#energy[energy['Country'] == 'Bolivia']

In [14]:
#old_values=["Republic of Korea","United States of America","United Kingdom of Great Britain and Northern Ireland","China, Hong Kong Special Administrative Region","Bolivia (Plurinational State of)"]  
#new_values=["South Korea","United States","United Kingdom","Hong Kong","Bolivia"]
#for o in old_values:
#        for n in new_values:
#            for i in energy.index:
#                energy=energy.replace(o,n)

### Step 1
<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

In [15]:
GDP = pd.read_csv('data/world_bank.csv',skiprows = range(0,4),header=0) 
GDP["Country Name"].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran",
                           "Hong Kong SAR, China": "Hong Kong"}, inplace=True)
GDP.rename(columns = {'Country Name' : 'Country'}, inplace = True)
GDP.head(50)

,Country,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
1,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
2,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
3,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
4,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
5,Arab World,ARB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
6,United Arab Emirates,ARE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
7,Argentina,ARG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.206739e+11,1.272239e+11,1.261399e+11,1.194442e+11,1.315442e+11,1.454477e+11,...,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
8,Armenia,ARM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
9,American Samoa,ASM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,ATG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
11,Australia,AUS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.983395e+11,2.032502e+11,2.059485e+11,2.187430e+11,2.340028e+11,2.479962e+11,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
12,Austria,AUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.223779e+10,9.734590e+10,9.992428e+10,1.040594e+11,1.104324e+11,1.142756e+11,...,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
13,Azerbaijan,AZE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
14,Burundi,BDI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.966083e+08,5.145977e+08,5.612365e+08,5.844459e+08,6.211084e+08,6.457492e+08,...,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
15,Belgium,BEL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.205638e+11,1.265660e+11,1.331626e+11,1.389573e+11,1.486241e+11,1.539161e+11,...,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
16,Benin,BEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.265426e+09,1.305177e+09,1.260456e+09,1.320076e+09,1.407871e+09,1.482402e+09,...,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
17,Burkina Faso,BFA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.120812e+09,1.166137e+09,1.237607e+09,1.221914e+09,1.249808e+09,1.296857e+09,...,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
18,Bangladesh,BGD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.786255e+10,1.894469e+10,1.997775e+10,1.988667e+10,2.206481e+10,2.241923e+10,...,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
19,Bulgaria,BGR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
20,Bahrain,BHR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
21,"Bahamas, The",BHS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.521892e+09,1.684234e+09,1.860270e+09,2.056046e+09,2.271963e+09,2.508828e+09,...,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
22,Bosnia and Herzegovina,BIH,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
23,Belarus,BLR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
24,Belize,BLZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.865406e+07,1.034805e+08,1.085434e+08,1.139233e+08,1.196193e+08,1.255172e+08,...,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
25,Bermuda,BMU,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.236025e+09,1.293871e+09,1.351707e+09,1.366170e+09,1.517951e+09,1.590206e+09,...,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
26,Bolivia,BOL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.818838e+09,4.919069e+09,5.193073e+09,5.526504e+09,5.791476e+09,6.117247e+09,...,1.644957e+10,1.720040e+10,1.825796e+10,1.887088e+10,1.964963e+10,2.067222e+10,2.173110e+10,2.320795e+10,2.447524e+10,2.544488e+10
27,Brazil,BRA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.466572e+11,2.720034e+11,2.861913e+11,2.886945e+11,2.987572e+11,3.078797e+11,...,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
28,Barbados,BRB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,4.490036e+09,4.490036e+09,4.498133e+09,4.542669e+09
29,Brunei Darussalam,BRN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249730e+10,1.251661e+10,1.227383e+10,1.205725e+10,1.237062e+10,1.279491e+10,1.291625e+10,1.268996e+10,1.239301e+10,1.233105e+10
30,Bhutan,BTN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.076853e+09,1.269887e+09,1.330440e+09,1.419010e+09,1.585473e+09,1.710581e+09,1.797337e+09,1.835844e+09,1.936060e+09,1.999064e+09
31,Botswana,BWA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.050106e+08,2.180150e+08,2.325494e+08,2.463187e+08,2.631480e+08,2.784473e+08,...,1.108667e+10,1.200467e+10,1.275401e+10,1.177803e+10,1.278666e+10,1.356004e+10,1.416434e+10,1.556098e+10,1.605954e+10,1.601864e+10
32,Central African Republic,CAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.147726e+08,9.600854e+08,9.244313e+08,9.178933e+08,9.369888e+08,9.458674e+08,...,1.774985e+09,1.856768e+09,1.894909e+09,1.927297e+09,1.986015e+09,2.051568e+09,2.111034e+09,1.329699e+09,1.312983e+09,1.385019e+09
33,Canada,CAN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.163370e+11,3.263436e+11,3.495688e+11,3.676827e+11,3.923154e+11,4.183516e+11,...,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
34,Central Europe and the Baltics,CEB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.210991e+12,1.289104e+12,1.336368e+12,1.286232e+12,1.311611e+12,1.352416e+12,1.359737e+12,1.377044e+12,1.415218e+12,1.463305e+12
35,Switzerland,CHE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.415550e+11,5.639773e+11,5.768204e+11,5.645363e+11,5.812117e+11,5.917000e+11,5.983544e+11,6.089383e+11,6.204440e+11,6.260878e+11
36,Channel Islands,CHI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Chile,CHL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.793838e+10,2.906986e+10,3.057948e+10,3.244990e+10,3.331562e+10,3.345460e+10,...,1.913560e+11,2.012316e+11,2.078570e+11,2.057027e+11,2.175383e+11,2.302417e+11,2.428063e+11,2.524617e+11,2.571989e+11,2.625130e+11
38,China,CHN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.262508e+11,9.178435e+10,8.664442e+10,9.548215e+10,1.129554e+11,1.321578e+11,...,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
39,Cote d'Ivoire,CIV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.289508e+09,4.715566e+09,4.773426e+09,5.465112e+09,6.427687e+09,6.227808e+09,...,2.263881e+10,2.303839e+10,2.362422e+10,2.439236e+10,2.488451e+10,2.379276e+10,2.634013e+10,2.876832e+10,3.122699e+10,3.386308e+10
40,Cameroon,CMR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.661608e+09,4.716786e+09,4.860250e+09,5.042147e+09,5.221000e+09,5.326781e+09,...,2.112444e+10,2.181218e+10,2.244126e+10,2.287479e+10,2.362248e+10,2.460059e+10,2.572945e+10,2.716044e+10,2.877023e+10,3.056526e+10
41,"Congo, Rep.",COG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.483222e+09,1.607082e+09,1.690687e+09,1.622565e+09,1.684495e+09,1.746424e+09,...,9.888363e+09,9.731907e+09,1.027419e+10,1.104156e+10,1.200788e+10,1.241862e+10,1.289053e+10,1.333406e+10,1.423810e+10,1.461490e+10
42,Colombia,COL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.647476e+10,3.839529e+10,4.049417e+10,4.167017e+10,4.442138e+10,4.575956e+10,...,2.453369e+11,2.622667e+11,2.715688e+11,2.760539e+11,2.870182e+11,3.059313e+11,3.183030e+11,3.338173e+11,3.484575e+11,3.591967e+11
43,Comoros,COM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.902586e+08,4.941814e+08,4.961594e+08,5.058345e+08,5.169629e+08,5.304039e+08,5.463160e+08,5.654371e+08,5.770944e+08,NaN
44,Cabo Verde,CPV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.352564e+09,1.557757e+09,1.661356e+09,1.640250e+09,1.664311e+09,1.730364e+09,1.749085e+09,1.767367e+09,1.816851e+09,1.862692e+09
45,Costa Rica,CRI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.566068e+09,3.531978e+09,3.819775e+09,4.002540e+09,4.168608e+09,4.578366e+09,...,3.151028e+10,3.401073e+10,3.493977e+10,3.458488e+10,3.629833e+10,3.793819e+10,3.989868e+10,4.127011e+10,4.271553e+10,4.389339e+10
46,Caribbean small states,CSS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.897028e+10,6.088163e+10,6.172341e+10,5.952123e+10,5.963144e+10,6.032654e+10,6.104798e+10,6.184883e+10,6.264199e+10,6.347025e+10
47,Cuba,CUB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.545431e+10,5.948147e+10,6.193022e+10,6.282767e+10,6.432820e+10,6.613130e+10,6.812475e+10,6.995461e+10,NaN,NaN
48,Curacao,CUW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Cayman Islands,CYM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 2
Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

In [16]:
ScimEn= pd.read_excel('data/scimagojr-3.xlsx')
ScimEn.head(50)

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57
5,6,Canada,17899,17620,215003,40930,12.01,149
6,7,Germany,17027,16831,140566,27426,8.26,126
7,8,India,15005,14841,128763,37209,8.58,115
8,9,France,13153,12973,130632,28601,9.93,114
9,10,South Korea,11983,11923,114675,22595,9.57,104
10,11,Italy,10964,10794,111850,26661,10.20,106
11,12,Spain,9428,9330,123336,23964,13.08,115
12,13,Iran,8896,8819,57470,19125,6.46,72
13,14,Australia,8831,8725,90765,15606,10.28,107
14,15,Brazil,8668,8596,60702,14396,7.00,86
15,16,Taiwan,6468,6441,86099,14768,13.31,102
16,17,Turkey,5879,5827,91857,23165,15.62,104
17,18,Norway,5675,5634,32693,6024,5.76,74
18,19,Netherlands,5170,5105,48351,6067,9.35,85
19,20,Sweden,4565,4494,57889,9632,12.68,95
20,21,Malaysia,3914,3881,25545,6597,6.53,62
21,22,Switzerland,3636,3599,38962,6186,10.72,81
22,23,Denmark,3531,3494,37254,6191,10.55,85
23,24,Mexico,3249,3214,21524,4145,6.62,57
24,25,Poland,3123,3102,24852,5395,7.96,55
25,26,Saudi Arabia,2979,2930,21208,2469,7.12,61
26,27,Greece,2866,2835,41662,6226,14.54,82
27,28,Egypt,2789,2752,19123,2778,6.86,55
28,29,Belgium,2697,2642,23720,3300,8.79,63
29,30,Singapore,2488,2443,36098,3700,14.51,81
30,31,Hong Kong,2448,2436,34453,3959,14.07,78
31,32,Portugal,2443,2426,22700,3639,9.29,63
32,33,Finland,1998,1978,19273,3260,9.65,59
33,34,South Africa,1928,1913,11924,1996,6.18,46
34,35,Austria,1761,1736,14580,1557,8.28,53
35,36,Ukraine,1744,1608,5073,1323,2.91,27
36,37,Romania,1738,1729,7100,1350,4.09,38
37,38,Thailand,1722,1712,19764,2600,11.48,62
38,39,Czech Republic,1608,1600,5630,1119,3.50,36
39,40,Argentina,1223,1213,10620,1654,8.68,47
40,41,Israel,1215,1202,14764,2051,12.15,54
41,42,Algeria,1215,1197,7393,1413,6.08,40
42,43,United Arab Emirates,1137,1124,6055,611,5.33,37
43,44,New Zealand,1092,1082,11504,1209,10.53,47
44,45,Colombia,1017,1014,7111,844,6.99,37
45,46,Nigeria,1017,1011,3559,684,3.50,29
46,47,Ireland,974,959,14361,1719,14.74,57
47,48,Venezuela,891,886,6109,693,6.86,41
48,49,Indonesia,833,827,3588,355,4.31,28
49,50,Kuwait,737,731,6101,651,8.28,39

### Step 3
Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This step should yeild a DataFrame with 20 columns and 15 entries.*

In [17]:

print('entries of energy',energy.shape[0])
print('entries of GDP',GDP.shape[0])
print('entries of ScimEn',ScimEn.shape[0])
Energy_GDP = pd.merge(energy,[GDP['Country','2006', '2007', '2008','2009','2010','2011','2012','2013','2014','2015']],on='Country')
Energy_GDP.set_index('Country', inplace = True)
print('entries of Energy_GDP',Energy_GDP.shape[0])
#Energy_GDP.head(90)

Energy_GDP_ScimEn=pd.merge(ScimEn[(ScimEn['Rank'] <= 15) ],Energy_GDP,on='Country')
Energy_GDP_ScimEn.set_index('Country', inplace = True)
#print('entries of Energy_GDP_ScimEn',Energy_GDP_ScimEn.shape[0])

print('shape of Energy_GDP_ScimEn',Energy_GDP_ScimEn.shape)
Energy_GDP_ScimEn.head(20)

entries of energy 227
entries of GDP 264
entries of ScimEn 191
entries of Energy_GDP 186
shape of Energy_GDP_ScimEn (15, 20)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

### Step 4
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This step should yield a single number.*

In [36]:
Energy_GDP_ScimEn_before_rank_filter=pd.merge(ScimEn,Energy_GDP,on='Country')
Energy_GDP_ScimEn_before_rank_filter.set_index('Country', inplace = True)
print('shape of Energy_GDP_ScimEnbefore_before_rank_filter',Energy_GDP_ScimEn_before_rank_filter.shape[0])
print('shape of Energy_GDP_ScimEn',Energy_GDP_ScimEn.shape[0])
print(Energy_GDP_ScimEn_before_rank_filter.shape[0]-Energy_GDP_ScimEn.shape[0])

shape of Energy_GDP_ScimEnbefore_before_rank_filter 162
shape of Energy_GDP_ScimEn 15
147

### Step 5

#### Answer the following questions in the context of only the top 15 countries by Scimagojr Rank 


What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This step should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [19]:
step5= Energy_GDP_ScimEn[['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']]
#avgGDP1=avgGDP.mean()
#avgGDP=Energy_GDP_ScimEn[Country].groupby('Country').sum()
#avgGDP.head(20)
avgGDP=step5.sum(axis = 1, skipna = True) / 10
avgGDP.sort_values(ascending=False)

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  3.997402e+11
dtype: float64

### Step  6
What is the mean `Energy Supply per Capita`?

*This step should return a single number.*

In [20]:
print(Energy_GDP_ScimEn['Energy Supply per Capita'].mean())

157.6

### Step 7
What country has the maximum % Renewable and what is the percentage?

*This step should return a tuple with the name of the country and the percentage.*

In [21]:
#Energy_GDP_ScimEn.head()
step7=Energy_GDP_ScimEn[['% Renewable']]

In [37]:
#step7[step7['% Renewable'] == step7['% Renewable'].max()]
t = (step7['% Renewable'].idxmax(), step7['% Renewable'].max())
print(t)

#print(step7[step7['% Renewable'] == step7['% Renewable'].idxmax()])

('Brazil', 69.64803)

### Step 8
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This step should return a tuple with the name of the country and the ratio.*

In [23]:
Energy_GDP_ScimEn['ratio of Self-Citations to Total Citations'] = Energy_GDP_ScimEn['Self-citations'] / Energy_GDP_ScimEn['Citations']
step8=Energy_GDP_ScimEn[['ratio of Self-Citations to Total Citations']]
#print(step8[step8['ratio of Self-Citations to Total Citations'] == step8['ratio of Self-Citations to Total Citations'].max()])
t1 = (step8['ratio of Self-Citations to Total Citations'].idxmax(), step8['ratio of Self-Citations to Total Citations'].max())
t1

('China', 0.6893126179389422)

### Step 9
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This step should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [24]:
#Energy_GDP_ScimEn.head()

Energy_GDP_ScimEn['HighRenew'] = Energy_GDP_ScimEn['% Renewable'].apply(lambda x : '1' if x >= Energy_GDP_ScimEn['% Renewable'].mean() else '0' )
HighRenew=Energy_GDP_ScimEn['HighRenew']
HighRenew.sort_values(ascending=False)

Country
Brazil                1
Spain                 1
Italy                 1
Canada                1
Australia             0
Iran                  0
South Korea           0
France                0
India                 0
Germany               0
Russian Federation    0
United Kingdom        0
Japan                 0
United States         0
China                 0
Name: HighRenew, dtype: object

### Step 10
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [25]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

In [26]:
#Energy_GDP_ScimEn.head(20)
#Continent_df = pd.DataFrame.from_dict(ContinentDict)
#Continent_df=pd.DataFrame.from_dict(ContinentDict, orient='index',columns=['continent'])
#print(Continent_df.groupby('continent').sum)
#ContinentDict
#Continent_df
#df_groupby_mean = ContinentDict.groupby('continent').mean()

#pd.qcut(Energy_GDP_ScimEn['ext price'], q=4)

#Continent_df=pd.DataFrame.from_dict(ContinentDict,columns=['country'], orient='index',)
#Continent_df

In [27]:
#Energy_GDP_ScimEn.head(20)

In [28]:
from pandas import DataFrame
df1 = pd.DataFrame(list(ContinentDict.items()),columns = ['country','continent'])
#df.set_index('continent')
df_groupby = df1.groupby('continent').count()
df_groupby.head(20)

               country
continent
Asia                 5
Australia            1
Europe               6
North America        2
South America        1

In [29]:
Energy_GDP_ScimEn['Population']=Energy_GDP_ScimEn['Energy Supply'] / Energy_GDP_ScimEn['Energy Supply per Capita'] 
Energy_GDP_ScimEn['Populationbymilion']=Energy_GDP_ScimEn['Population'] / 1000000
Energy_GDP_ScimEn.head(20)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2010,2011,2012,2013,2014,2015,ratio of Self-Citations to Total Citations,HighRenew,Population,Populationbymilion
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,...,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,0,1.367645e+09,1367.645161
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,...,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,0,3.176154e+08,317.615385
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,...,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,0,1.274094e+08,127.409396
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,...,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,0,6.387097e+07,63.870968
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,...,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,0,1.435000e+08,143.500000
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,...,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,1,3.523986e+07,35.239865
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,...,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,0,8.036970e+07,80.369697
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,...,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,0,1.276731e+09,1276.730769
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,...,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,0,6.383735e+07,63.837349
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,...,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,0,4.980543e+07,49.805430
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,...,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,1,5.990826e+07,59.908257
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,...,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,1,4.644340e+07,46.443396
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,...,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,0,7.707563e+07,77.075630
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,...,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,0,2.331602e+07,23.316017
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,...,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,1,2.059153e+08,205.915254

In [30]:
from pandas import DataFrame
df2 = pd.DataFrame(list(ContinentDict.items()),columns = ['Country','continent'])
#df2.set_index('Country', inplace = True)
df2.head(20)

               Country      continent
0                China           Asia
1        United States  North America
2                Japan           Asia
3       United Kingdom         Europe
4   Russian Federation         Europe
5               Canada  North America
6              Germany         Europe
7                India           Asia
8               France         Europe
9          South Korea           Asia
10               Italy         Europe
11               Spain         Europe
12                Iran           Asia
13           Australia      Australia
14              Brazil  South America

In [31]:
merged = pd.merge(df2,Energy_GDP_ScimEn['Population'], on='Country' )
merged.head(20)

               Country      continent    Population
0                China           Asia  1.367645e+09
1        United States  North America  3.176154e+08
2                Japan           Asia  1.274094e+08
3       United Kingdom         Europe  6.387097e+07
4   Russian Federation         Europe  1.435000e+08
5               Canada  North America  3.523986e+07
6              Germany         Europe  8.036970e+07
7                India           Asia  1.276731e+09
8               France         Europe  6.383735e+07
9          South Korea           Asia  4.980543e+07
10               Italy         Europe  5.990826e+07
11               Spain         Europe  4.644340e+07
12                Iran           Asia  7.707563e+07
13           Australia      Australia  2.331602e+07
14              Brazil  South America  2.059153e+08

In [32]:
#rnm_cols = dict(size='Size', sum='Sum', mean='Mean', std='Std')
#merged.set_index(['continent', 'Country']).stack().groupby('continent').agg(rnm_cols.keys()).rename(columns=rnm_cols)

In [33]:
#agg_funcs = dict(Size='size', Sum='sum', Mean='mean', Std='std')
#merged.set_index(['continent', 'Country']).stack().groupby(level=0).agg(agg_funcs)

In [34]:
#merged.set_index(['continent', 'Country']).stack().groupby(level=0).describe().stack()

In [35]:
#merged_groupby = merged.groupby('continent')
#merged_groupby.head(20)
import numpy as np
# multi-level groupby
merged_groupby = merged.groupby('continent').agg([np.size,np.sum, np.mean, np.std])
# check 
merged_groupby.head(20)

              Population
                    size           sum          mean           std
continent
Asia                 5.0  2.898666e+09  5.797333e+08  6.790979e+08
Australia            1.0  2.331602e+07  2.331602e+07           NaN
Europe               6.0  4.579297e+08  7.632161e+07  3.464767e+07
North America        2.0  3.528552e+08  1.764276e+08  1.996696e+08
South America        1.0  2.059153e+08  2.059153e+08           NaN